export const ABRIR_CERRAR_ASIDE = "ABRIR_CERRAR_ASIDE"; 

export const OBTENER_PELICULAS = "OBTENER_PELICULAS";
export const OBTENER_PELICULA = "OBTENER_PELICULA";
export const SELECCIONAR_PELICULA = "SELECCIONAR_PELICULA";